# conf/base/parameters.yml
seed: 4322

train:
  N: 9
  lower_bound: 0.0
  upper_bound: 1.0

val:
  N: 100
  lower_bound: 0.0
  upper_bound: 1.0

test:
  N: 100
  lower_bound: 0.0
  upper_bound: 1.0

noise_std: 0.2
frequency: 2.0   # for sin(2*pi*frequency*x)
